name: Mancations
favicon: null
layout_spectrum: 0.7734871122520417
typography_spectrum: 0.07495168363675475
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7984319822862744
  lightness: 0.7578018186613917
  saturation: 0.4516032466199249
  rhythmicContrast: 0.282035760814324
purpose: []
